export const Accesstoken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYW5kaWRhdGVfbmFtZSI6InJhaHVsLmJpc2h0MDA3QGFpZGV0aWMuaW4iLCJpc19jYW5kaWRhdGUiOnRydWUsImlhdCI6MTY5MTQwNjc5NCwiZXhwIjoxNjkxOTI1MTk0fQ.gLK10-BuukbZeK4WHDB6PO3nEaa1JlN6VMmN_vObP0I';
export const Endpoint = 'https://api.poc.graphql.dev.vnplatform.com/graphql';
